# tests/test_chart_crosshair_ownership.py
"""Crosshair generation, stale callbacks, and pointer coalescing.

Python tests inspect JavaScript generated by the production function.
Optional Node tests execute that JavaScript with ECharts-shaped doubles.
Neither layer claims to verify real NiceGUI browser rendering.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from types import SimpleNamespace

import pytest

import l2shock.ui.chart_interactions as interactions

_TOKEN = "a" * 32


async def _capture_script(
    monkeypatch: pytest.MonkeyPatch,
    *,
    chart_id: int = 101,
    token: str = _TOKEN,
) -> tuple[bool, list[str]]:
    scripts: list[str] = []

    async def run_javascript(
        script: str,
        *,
        timeout: float,
    ) -> dict[str, object]:
        assert timeout == 6.0
        scripts.append(script)
        return {"ok": True}

    monkeypatch.setattr(
        interactions.ui,
        "run_javascript",
        run_javascript,
    )
    monkeypatch.setattr(
        interactions,
        "acknowledged_render_token",
        lambda _chart: token,
    )

    chart = SimpleNamespace(id=chart_id)

    result = await interactions.install_analysis_gapped_crosshair(
        chart,
        expected_render_token=token,
    )

    return result, scripts


@pytest.mark.asyncio
async def test_generated_crosshair_uses_chart_scoped_generations(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    installed, scripts = await _capture_script(monkeypatch)

    assert installed is True
    assert len(scripts) == 1

    script = scripts[0]

    assert "state.generations[key]" in script
    assert "generation === state.generations[key]" in script
    assert "generation !== state.generations[key]" in script
    assert "state.generation =" not in script
    assert "generation !== state.generation\n" not in script


@pytest.mark.asyncio
async def test_generated_crosshair_guards_removal_and_latest_pointer(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    installed, scripts = await _capture_script(monkeypatch)

    assert installed is True

    script = scripts[0]

    assert "if (!instance || !ownsInstallation(instance)) return;" in script
    assert "latestPointer = pointer;" in script
    assert "draw(instance, latestPointer);" in script
    assert "Number(state.raf[key] || 0) !== frameId" in script
    assert "const previousFrame = Number(state.raf[key] || 0);" in script
    assert "cancelAnimationFrame(previousFrame);" in script


@pytest.mark.asyncio
async def test_crosshair_without_acknowledged_owner_runs_no_javascript(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    calls: list[str] = []

    async def run_javascript(
        script: str,
        *,
        timeout: float,
    ) -> None:
        del timeout
        calls.append(script)
        raise AssertionError("Unacknowledged chart executed JavaScript")

    monkeypatch.setattr(
        interactions.ui,
        "run_javascript",
        run_javascript,
    )
    monkeypatch.setattr(
        interactions,
        "acknowledged_render_token",
        lambda _chart: "",
    )

    installed = await interactions.install_analysis_gapped_crosshair(
        SimpleNamespace(id=101),
        expected_render_token=_TOKEN,
    )

    assert installed is False
    assert calls == []


_NODE_HARNESS = r"""
"use strict";

const fs = require("node:fs");
const vm = require("node:vm");

const payload = JSON.parse(fs.readFileSync(0, "utf8"));
const frames = new Map();
const charts = new Map();
let nextFrame = 0;

class Element {
    constructor(id) {
        this.id = id;
        this.nodeType = 1;
        this.parentElement = null;
    }

    querySelectorAll() {
        return [];
    }
}

function requireCondition(condition, message) {
    if (!condition) {
        throw new Error(message);
    }
}

function makeChart(id, token) {
    const root = new Element(id);
    const handlers = new Map();
    const writes = [];
    const graphics = new Map();

    const renderer = {
        on(name, handler) {
            if (!handlers.has(name)) {
                handlers.set(name, new Set());
            }
            handlers.get(name).add(handler);
        },

        off(name, handler) {
            if (handlers.has(name)) {
                handlers.get(name).delete(handler);
            }
        },
    };

    const chart = {
        root,
        token,
        writes,
        graphics,

        getOption() {
            return {
                series: [
                    {
                        name: "__l2shock_render_token__:" + this.token,
                    },
                ],
            };
        },

        getModel() {
            return {
                getComponent(kind, index) {
                    requireCondition(kind === "grid", "Unexpected component");
                    return {
                        coordinateSystem: {
                            getRect() {
                                return {
                                    x: 0,
                                    y: index * 100,
                                    width: 200,
                                    height: 80,
                                };
                            },
                        },
                    };
                },
            };
        },

        getZr() {
            return renderer;
        },

        setOption(option) {
            writes.push(option);

            for (const item of option.graphic || []) {
                if (item.$action === "remove") {
                    graphics.delete(item.id);
                } else {
                    graphics.set(
                        item.id,
                        Object.assign({}, graphics.get(item.id) || {}, item),
                    );
                }
            }
        },

        emit(name, event) {
            const current = handlers.get(name);
            if (!current) return;

            for (const handler of Array.from(current)) {
                handler(event);
            }
        },
    };

    charts.set(String(id), chart);
    return chart;
}

const sandbox = {
    window: {},
    HTMLElement: Element,

    document: {
        getElementById(id) {
            const key = String(id).replace(/^c/, "");
            const chart = charts.get(key);
            return chart ? chart.root : null;
        },
    },

    getElement(id) {
        const chart = charts.get(String(id));
        return chart ? chart.root : null;
    },

    echarts: {
        getInstanceByDom(root) {
            const chart = charts.get(String(root.id));
            return chart || null;
        },
    },

    requestAnimationFrame(callback) {
        const id = ++nextFrame;
        frames.set(id, callback);
        return id;
    },

    cancelAnimationFrame(id) {
        frames.delete(id);
    },

    setTimeout() {
        throw new Error("Unexpected crosshair installation retry");
    },
};

const context = vm.createContext(sandbox);

function install(index) {
    return vm.runInContext(
        payload.scripts[index],
        context,
        {timeout: 2000},
    );
}

function flushFrame(id) {
    const callback = frames.get(id);
    requireCondition(typeof callback === "function", "Missing frame");
    frames.delete(id);
    callback();
}

function lastVerticalX(chart) {
    const option = chart.writes[chart.writes.length - 1];
    requireCondition(option, "No graphic write");

    const line = option.graphic.find(
        item => item.id === "l2shock_crosshair_v_1"
            && item.shape,
    );

    requireCondition(line, "Missing panel-one crosshair");
    return line.shape.x1;
}

const first = makeChart(101, "a".repeat(32));

if (payload.scenario === "multiple_charts") {
    const second = makeChart(202, "b".repeat(32));

    install(0);

    first.emit("mousemove", {offsetX: 25, offsetY: 140});
    const firstFrame = sandbox.window.__l2shockAnalysisCrosshair.raf["101"];

    install(1);

    flushFrame(firstFrame);

    requireCondition(
        lastVerticalX(first) === 25,
        "Installing another chart invalidated the first chart",
    );

    second.emit("mousemove", {offsetX: 65, offsetY: 140});
    flushFrame(sandbox.window.__l2shockAnalysisCrosshair.raf["202"]);

    requireCondition(
        lastVerticalX(second) === 65,
        "Second chart did not draw independently",
    );
} else if (payload.scenario === "latest_pointer") {
    install(0);

    first.emit("mousemove", {offsetX: 25, offsetY: 140});
    const frame = sandbox.window.__l2shockAnalysisCrosshair.raf["101"];

    first.emit("mousemove", {offsetX: 75, offsetY: 140});

    requireCondition(frames.size === 1, "Pointer events queued extra frames");

    flushFrame(frame);

    requireCondition(
        lastVerticalX(first) === 75,
        "Frame did not draw the latest pointer",
    );
} else if (payload.scenario === "stale_callbacks") {
    install(0);

    const oldHandlers = first.__l2shockGappedCrosshairHandlers;

    first.emit("mousemove", {offsetX: 25, offsetY: 140});
    const oldFrame = sandbox.window.__l2shockAnalysisCrosshair.raf["101"];
    const oldCallback = frames.get(oldFrame);

    // Reinstall on the same acknowledged render token. Installation
    // generation still changes, so old callbacks must become inert.
    install(0);

    requireCondition(
        !frames.has(oldFrame),
        "Replacement did not cancel the old pending frame",
    );

    first.emit("mousemove", {offsetX: 80, offsetY: 140});
    const newFrame = sandbox.window.__l2shockAnalysisCrosshair.raf["101"];
    const before = first.writes.length;

    // Explicitly invoke obsolete callbacks to test the ownership guard,
    // even though normal cancellation/detachment already prevents them.
    oldCallback();
    oldHandlers.globalout();

    requireCondition(
        first.writes.length === before,
        "Obsolete callback changed the replacement's graphics",
    );
    requireCondition(
        sandbox.window.__l2shockAnalysisCrosshair.raf["101"] === newFrame,
        "Obsolete callback cleared the replacement's frame ownership",
    );
    requireCondition(
        frames.has(newFrame),
        "Obsolete globalout cancelled the replacement's frame",
    );

    flushFrame(newFrame);

    requireCondition(
        lastVerticalX(first) === 80,
        "Replacement frame failed after obsolete callback invocation",
    );
} else if (payload.scenario === "current_globalout") {
    install(0);

    first.emit("mousemove", {offsetX: 25, offsetY: 140});
    const frame = sandbox.window.__l2shockAnalysisCrosshair.raf["101"];

    first.emit("globalout");

    requireCondition(!frames.has(frame), "Current globalout left a frame queued");
    requireCondition(
        sandbox.window.__l2shockAnalysisCrosshair.raf["101"] === 0,
        "Current globalout did not clear its frame",
    );

    const removal = first.writes[first.writes.length - 1];

    requireCondition(
        removal && removal.graphic.every(item => item.$action === "remove"),
        "Current globalout did not remove crosshair graphics",
    );
} else if (payload.scenario === "price_panel_transition") {
    install(0);

    const gappedIds = [
        "l2shock_crosshair_price_v_top",
        "l2shock_crosshair_price_v_bottom",
        "l2shock_crosshair_price_h_left",
        "l2shock_crosshair_price_h_right",
    ];

    // Exercise every L2 panel -> Price transition without leaving the
    // chart. No globalout cleanup should be required for correctness.
    for (let panel = 1; panel < 5; panel += 1) {
        first.emit("mousemove", {
            offsetX: 75,
            offsetY: panel * 100 + 40,
        });
        flushFrame(sandbox.window.__l2shockAnalysisCrosshair.raf["101"]);

        requireCondition(
            first.graphics.has("l2shock_crosshair_v_0"),
            "L2 hover did not create the full Price vertical line",
        );

        for (const id of gappedIds) {
            requireCondition(
                !first.graphics.has(id),
                "L2 hover retained a gapped Price element",
            );
        }

        first.emit("mousemove", {offsetX: 75, offsetY: 40});
        flushFrame(sandbox.window.__l2shockAnalysisCrosshair.raf["101"]);

        requireCondition(
            !first.graphics.has("l2shock_crosshair_v_0"),
            "Price hover retained the full vertical line across its gap",
        );

        for (const id of gappedIds) {
            requireCondition(
                first.graphics.has(id),
                "Price hover did not create a gapped crosshair element",
            );
        }

        for (let other = 1; other < 5; other += 1) {
            requireCondition(
                first.graphics.has("l2shock_crosshair_v_" + other),
                "Price hover lost a synchronized L2 vertical line",
            );
        }
    }

    first.emit("globalout");

    requireCondition(
        first.graphics.size === 0,
        "Globalout left crosshair graphic state behind",
    );
} else {
    throw new Error("Unknown scenario");
}

process.stdout.write(JSON.stringify({ok: true, scenario: payload.scenario}));
"""


@pytest.mark.asyncio
@pytest.mark.parametrize(
    "scenario",
    [
        "multiple_charts",
        "latest_pointer",
        "stale_callbacks",
        "current_globalout",
        "price_panel_transition",
    ],
)
async def test_generated_crosshair_javascript_behavior(
    monkeypatch: pytest.MonkeyPatch,
    scenario: str,
) -> None:
    node = shutil.which("node")

    if node is None:
        pytest.skip("Optional Node.js runtime is not installed")

    _, first_scripts = await _capture_script(
        monkeypatch,
        chart_id=101,
        token="a" * 32,
    )
    _, second_scripts = await _capture_script(
        monkeypatch,
        chart_id=202,
        token="b" * 32,
    )

    payload = json.dumps(
        {
            "scenario": scenario,
            "scripts": [
                first_scripts[0],
                second_scripts[0],
            ],
        }
    )

    completed = subprocess.run(
        [node, "-e", _NODE_HARNESS],
        input=payload,
        text=True,
        capture_output=True,
        timeout=10,
        check=False,
    )

    assert completed.returncode == 0, (
        f"JavaScript harness failed for {scenario}:\n"
        f"{completed.stdout}\n{completed.stderr}"
    )

    assert json.loads(completed.stdout) == {
        "ok": True,
        "scenario": scenario,
    }


@pytest.mark.asyncio
async def test_price_hover_explicitly_removes_full_price_vertical(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    installed, scripts = await _capture_script(monkeypatch)

    assert installed is True
    assert len(scripts) == 1

    script = scripts[0]
    price_branch = script.split(
        "if (hoveredPanel === 0) {",
        1,
    )[1].split(
        "} else {",
        1,
    )[0]

    full_vertical = price_branch.index('id: "l2shock_crosshair_v_0"')
    removal = price_branch.index(
        '$action: "remove"',
        full_vertical,
    )
    first_gapped_line = price_branch.index('"l2shock_crosshair_price_v_top"')

    assert full_vertical < removal < first_gapped_line
