# l2shock/remote/__init__.py
"""Remote processed-artifact contracts and pure transport codecs."""

from l2shock.remote.artifact_codec import (
    REMOTE_ARTIFACT_PARQUET_CODEC,
    REMOTE_ARTIFACT_PARQUET_SCHEMA,
    REMOTE_ARTIFACT_PARQUET_SCHEMA_VERSION,
    RemoteArtifactCodecError,
    RemoteArtifactCorruptionError,
    RemoteArtifactFileInfo,
    RemoteArtifactLimitError,
    RemoteL2ProcessedArtifact,
    RemotePriceProcessedArtifact,
    RemoteProcessedArtifact,
    read_remote_artifact_file,
    write_remote_artifact_file,
)
from l2shock.remote.headless_processing import (
    HeadlessL2ProcessingOutput,
    HeadlessPriceProcessingOutput,
    process_l2_archive_headlessly,
    process_price_archives_headlessly,
)
from l2shock.remote.hf_repository import (
    DownloadedHuggingFaceArtifact,
    HuggingFaceArtifactConflictError,
    HuggingFaceArtifactNotFoundError,
    HuggingFaceDatasetRepository,
    HuggingFacePartialArtifactError,
    HuggingFacePredecessorCheckpoint,
    HuggingFacePublicationError,
    HuggingFacePublicationResult,
    HuggingFaceRepositoryError,
    HuggingFaceRepositoryUnavailableError,
)
from l2shock.remote.source_acquisition import (
    RemoteWorkerAcquisitionError,
    RemoteWorkerAcquisitionResult,
    RemoteWorkerSourceNotEligibleError,
    RemoteWorkerWorkspace,
    acquire_remote_worker_archives,
    build_remote_worker_workspace,
    temporary_remote_worker_workspace,
)
from l2shock.remote.contracts import (
    REMOTE_ARTIFACT_SCHEMA,
    REMOTE_ARTIFACT_SCHEMA_VERSION,
    RemoteArtifactKey,
    RemoteArtifactKind,
    RemoteArtifactManifest,
    RemoteContractError,
    RemoteSourceHourReference,
)

__all__ = [
    "REMOTE_ARTIFACT_PARQUET_CODEC",
    "REMOTE_ARTIFACT_PARQUET_SCHEMA",
    "REMOTE_ARTIFACT_PARQUET_SCHEMA_VERSION",
    "REMOTE_ARTIFACT_SCHEMA",
    "REMOTE_ARTIFACT_SCHEMA_VERSION",
    "DownloadedHuggingFaceArtifact",
    "HeadlessL2ProcessingOutput",
    "HeadlessPriceProcessingOutput",
    "HuggingFaceArtifactConflictError",
    "HuggingFaceArtifactNotFoundError",
    "HuggingFaceDatasetRepository",
    "HuggingFacePartialArtifactError",
    "HuggingFacePredecessorCheckpoint",
    "HuggingFacePublicationError",
    "HuggingFacePublicationResult",
    "HuggingFaceRepositoryError",
    "HuggingFaceRepositoryUnavailableError",
    "RemoteArtifactCodecError",
    "RemoteArtifactCorruptionError",
    "RemoteArtifactFileInfo",
    "RemoteArtifactKey",
    "RemoteArtifactKind",
    "RemoteArtifactLimitError",
    "RemoteArtifactManifest",
    "RemoteContractError",
    "RemoteL2ProcessedArtifact",
    "RemotePriceProcessedArtifact",
    "RemoteProcessedArtifact",
    "RemoteSourceHourReference",
    "RemoteWorkerAcquisitionError",
    "RemoteWorkerAcquisitionResult",
    "RemoteWorkerSourceNotEligibleError",
    "RemoteWorkerWorkspace",
    "acquire_remote_worker_archives",
    "build_remote_worker_workspace",
    "process_l2_archive_headlessly",
    "process_price_archives_headlessly",
    "read_remote_artifact_file",
    "temporary_remote_worker_workspace",
    "write_remote_artifact_file",
]
