# l2shock/price/__init__.py
"""Real Binance Futures trade-price construction and block encoding."""

from l2shock.price.block_codec import (
    PRICE_BLOCK_CODEC,
    PRICE_BLOCK_FORMAT_VERSION,
    PRICE_BLOCK_MAGIC,
    DecodedHourlyTradeOHLCChannels,
    EncodedHourlyTradeOHLCBlocks,
    PriceBlockChannel,
    PriceBlockCodecError,
    PriceBlockCorruptionError,
    PriceBlockLimitError,
    PriceInvalidReasonCode,
    PriceQualityCode,
    decode_hourly_trade_ohlc_blocks,
    encode_hourly_trade_ohlc_block,
    trade_ohlc_quality_summary_to_dict,
    verify_hourly_trade_ohlc_blocks,
)
from l2shock.price.hourly import (
    MILLISECONDS_PER_HOUR,
    MILLISECONDS_PER_SECOND,
    PRICE_OBSERVATIONS_PER_HOUR,
    HourlyTradeOHLCBlock,
    OneSecondTradeOHLCAccumulator,
    StreamedTradeOHLCResult,
    TradeOHLCCancelledError,
    TradeOHLCError,
    TradeOHLCObservation,
    TradeOHLCQualitySummary,
    TradeSampleInvalidReason,
    TradeSampleQuality,
    build_trade_ohlc_hour,
    build_trade_ohlc_quality_summary,
    stream_trade_ohlc_hour,
)

__all__ = [
    "MILLISECONDS_PER_HOUR",
    "MILLISECONDS_PER_SECOND",
    "PRICE_BLOCK_CODEC",
    "PRICE_BLOCK_FORMAT_VERSION",
    "PRICE_BLOCK_MAGIC",
    "PRICE_OBSERVATIONS_PER_HOUR",
    "DecodedHourlyTradeOHLCChannels",
    "EncodedHourlyTradeOHLCBlocks",
    "HourlyTradeOHLCBlock",
    "OneSecondTradeOHLCAccumulator",
    "PriceBlockChannel",
    "PriceBlockCodecError",
    "PriceBlockCorruptionError",
    "PriceBlockLimitError",
    "PriceInvalidReasonCode",
    "PriceQualityCode",
    "StreamedTradeOHLCResult",
    "TradeOHLCCancelledError",
    "TradeOHLCError",
    "TradeOHLCObservation",
    "TradeOHLCQualitySummary",
    "TradeSampleInvalidReason",
    "TradeSampleQuality",
    "build_trade_ohlc_hour",
    "build_trade_ohlc_quality_summary",
    "decode_hourly_trade_ohlc_blocks",
    "encode_hourly_trade_ohlc_block",
    "stream_trade_ohlc_hour",
    "trade_ohlc_quality_summary_to_dict",
    "verify_hourly_trade_ohlc_blocks",
]
