# l2shock/presets/__init__.py
"""Deterministic identities for materialized analytical data presets."""

from l2shock.presets.identity import (
    DATA_PRESET_AGGREGATION_POLICY,
    DATA_PRESET_ALGORITHM_VERSION,
    DATA_PRESET_NOTIONAL_CONVENTION,
    DATA_PRESET_QUALITY_POLICY,
    DATA_PRESET_SAMPLING_CLOCK,
    DATA_PRESET_SAMPLING_INTERVAL_MS,
    DATA_PRESET_SCHEMA,
    DATA_PRESET_SCHEMA_VERSION,
    DataPresetError,
    EligibleMarket,
    LiquidityDataPreset,
    MarketType,
    SettlementType,
    build_binance_futures_data_preset,
    build_bybit_data_preset,
    build_okx_futures_data_preset,
    build_binance_okx_futures_data_preset,
    component_data_presets,
    liquidity_data_preset_from_canonical_dict,
)
from l2shock.presets.management import (
    ManagedPreset,
    ManagedPresetWriteResult,
    PresetManagementError,
    PresetMarketProfile,
    create_edited_preset,
    create_managed_preset,
    delete_managed_preset,
    list_managed_presets,
    set_managed_preset_enabled,
)

__all__ = [
    "DATA_PRESET_AGGREGATION_POLICY",
    "DATA_PRESET_ALGORITHM_VERSION",
    "DATA_PRESET_NOTIONAL_CONVENTION",
    "DATA_PRESET_QUALITY_POLICY",
    "DATA_PRESET_SAMPLING_CLOCK",
    "DATA_PRESET_SAMPLING_INTERVAL_MS",
    "DATA_PRESET_SCHEMA",
    "DATA_PRESET_SCHEMA_VERSION",
    "DataPresetError",
    "EligibleMarket",
    "LiquidityDataPreset",
    "MarketType",
    "SettlementType",
    "ManagedPreset",
    "ManagedPresetWriteResult",
    "PresetManagementError",
    "PresetMarketProfile",
    "create_edited_preset",
    "create_managed_preset",
    "delete_managed_preset",
    "list_managed_presets",
    "set_managed_preset_enabled",
    "build_binance_futures_data_preset",
    "build_bybit_data_preset",
    "build_okx_futures_data_preset",
    "build_binance_okx_futures_data_preset",
    "component_data_presets",
    "liquidity_data_preset_from_canonical_dict",
]
